version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.7
        commands:
            - cd reversi
            - echo Start installation
        # setup for Ubuntu env
            - apt update
            - apt install sudo
            - apt install -y python3-dev
        # install python libraries
            - pip install pipenv
            - sudo apt install 
            - pipenv install --dev
        # install js libraries
            - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            - sudo apt install -y nodejs
            - npm install
            - npm install --only=dev
            - echo Finish installation
        # install redis
            - sudo apt install -y redis-server

    build:
        commands:
            - echo Build started on `date`
        # build js code
            - npm run build
        # setup django application
            - cp reversi/settings/local.py.example reversi/settings/local.py
            - cp .env.example .env
            - pipenv run python manage.py makemigrations
            - pipenv run python manage.py migrate
        # run redis server for test
            - sudo redis-server --protected-mode no &
            - sudo redis-cli ping
        # test python (django) code
            - pipenv run python manage.py test
        # test python (pytest) code
            - pipenv run pytest --ignore=node_modules
        # test js code
            - npm run test
        # check js code format
            - npm run check
        # static js code analysis
            - npm run lint
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        - reversi/assets/webpack_bundles/**/*
