# Generated by Django 2.2.2 on 2019-10-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
