# Generated by Django 2.2.2 on 2019-12-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversiapp', '0003_auto_20191028_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombelongings',
            name='is_black_stone_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roombelongings',
            name='is_white_stone_user',
            field=models.BooleanField(default=False),
        ),
    ]
